@startuml usecase
' skinparam linetype ortho

left to right direction

        skinparam ArrowColor Blue


:StakeHolder: as usuario
:Autor: as autor
:Acadêmico: as usuario
:Admnistrador: as admnistrador

usuario <|-right- autor
' usuario <|-- usuario
usuario <|-- admnistrador

rectangle sistema {
        rectangle conta {
            usuario -right- (criar conta)
            usuario -right- (recuperar senha)
            usuario -right- (autenticar)
            admnistrador -down- (excluir conta)
        }

        rectangle midia {

            admnistrador -right--- (remover mídia)

            autor -up- (remover mídia)
            autor -up- (atualizar midia)

            (autenticar) <.up. (interagir com midia) :includes

            (interagir com midia) <.up. (remover mídia) : extends
            (interagir com midia) <.up. (atualizar midia) : extends
            (interagir com midia) <.up. (visualizar mídia) : extends
            (interagir com midia) <.up. (executar mídia) : extends
            (interagir com midia) <.up. (comprar mídia) : extends
            (interagir com midia) <.up. (vender mídia) : extends
            (interagir com midia) <.up. (download mídia) : extends
            (interagir com midia) <.up. (classificar mídia) : extends
            (interagir com midia) <.up. (executar buscas refinadas de mídia) : extends

            (comprar mídia) ..> (emitir comprovante) : includes

            usuario -- (visualizar mídia)
            usuario -- (executar mídia)
            usuario -- (comprar mídia)
            usuario -- (vender mídia)
            usuario -- (download mídia)
            usuario -- (classificar mídia)
            usuario -- (executar buscas refinadas de mídia)
        }

        rectangle lista {
            usuario -- (criar lista)
            usuario -- (visualizar lista) 
            usuario -- (atualizar lista) 
            usuario -- (remover midia da lista) 

            (autenticar) <.. (interagir com lista) : includes

            (interagir com lista) <.up. (criar lista) : extends
            (interagir com lista) <.up. (visualizar lista) : extends
            (interagir com lista) <.up. (atualizar lista) : extends
            (interagir com lista) <.up. (remover midia da lista) : extends

        }
        
        rectangle album {
            autor -- (criar album)
            usuario -- (visualizar albuns)

            (autenticar) <... (interagir com albums) : includes            

            (interagir com albums) <.up. (criar album) : extends
            (interagir com albums) <.up. (visualizar albuns) : extends

            (visualizar albuns) <.left. (visualizar albuns novos) : extends
            (visualizar albuns) <.right. (visualizar albuns recentes) : extends
            (visualizar albuns) <.up. (visualizar todos os albuns) : extends
        }

        rectangle credito {
            usuario -- (visualizar créditos)
            usuario -- (adicionar créditos)

            (autenticar) <.. (visualizar créditos) : includes
            (autenticar) <.. (adicionar créditos) : includes

            (adicionar créditos) <.. (via cartão de crédito) : extends
            (adicionar créditos) <.. (via bolet bancário) : extends
            (adicionar créditos) <.. (via transferência bancária) : extends
        }

        ' rectangle adm {
        '     admnistrador -up- (acompanhar vendas)
        ' }
}

@enduml